[package]
name = "flowscad"
version = "0.2.0"
authors = [ "Thomas G. Draper" ]
edition = "2021"
rust-version = "1.81"
description = "2D graphic and 3D object design with a Rustic functional approach. SVG and OpenSCAD output."
documentation = "https://docs.rs/flowscad"
readme = "README.md"
repository = "https://github.com/SmoothDragon/rust_scad"
license = "LGPL-3.0-or-later"
keywords = ["scad", "svg", "graphics", "2D", "3D"]
categories = ["graphics", "mathematics"]
exclude = ["/gallery"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
derive_more = "0.99.18"
itertools = "0.12.1"
qhull = "0.3.1"
rand = "0.8.5"
rand_distr = "0.4.3"
typed_floats = "1.0.2"

# `path` is used locally; `version` is what ends up on crates.io.
# Requires `bitperm 0.2.0` to be published before `cargo publish` will succeed here.
bitperm = { path = "../bitperm", version = "0.2.0" }
ndarray = "0.17.1"
num-complex = "0.4.6"
libm = "0.2.15"

